- name: make sure the /etc/bigboards directory exists
  file: path="/etc/bigboards" state="directory" owner="bb" mode="755"

- name: make sure the hex.yml file exists
  template: src=hex.yml.j2 dest=/etc/bigboards/hex.yml owner=bb mode=755

- name: get the nodejs install script
  get_url:
    url: https://deb.nodesource.com/setup_6.x
    dest: /tmp/setup_6.x
    mode: 777

- name: install nodejs repos
  shell: /tmp/setup_6.x creates=/etc/apt/sources.list.d/nodesource.list

- name: install nodejs
  apt: name=nodejs=6.7* update_cache=yes state=present