---
- hosts: local
  sudo: yes
  tasks:
    - name: be sure the tint directory exists
      file: state=directory path=/opt/bb/tints.d/stack

    - name: be sure the tint sources are available
      git: repo={{ tint.uri }} dest=/opt/bb/tints.d/stack/{{ tint.owner }}/{{ tint.id }}

    - name: be sure the tint variables have been read
      include_vars: /opt/bb/tints.d/stack/{{ tint.owner }}/{{ tint.id }}/tint.yml

    - name: generate the hosts file
      template: src=hosts.j2 dest=/opt/bb/tints.d/stack/{{ tint.owner }}/{{ tint.id }}/hosts

    - name: be sure the group vars directory exists
      file: state=directory path=/opt/bb/tints.d/stack/{{ tint.owner }}/{{ tint.id }}/group_vars

    - name: generate the mapping file
      template: src=mapping.yml.j2 dest=/opt/bb/tints.d/stack/{{ tint.owner }}/{{ tint.id }}/mapping.yml

    - name: generate the group variables file
      template: src=vars.j2 dest=/opt/bb/tints.d/stack/{{ tint.owner }}/{{ tint.id }}/group_vars/all