#!/bin/bash

function moduleExecute() {
    sudo service bigboards-mmc $3
    return $?
}

function commandInfo() {
    echo "      mmc             Start, stop or restart the mmc console. "
    echo
    echo "                      ARGUMENTS:"
    echo "                      command     one of 'start', 'stop', 'restart' or 'status'"
    echo
}