#!/bin/bash

function moduleInfo() {
    echo
    echo "MODULE: firmware"
    echo

    for file in `ls ${DIR}/ansible/firmware/`; do
        if [ -e "${DIR}/ansible/firmware/$file/command" ]; then
            source "${DIR}/ansible/firmware/$file/command"
            commandInfo
        fi
    done
}