---
- hosts: host-coordinators
  sudo: yes
  tasks:
    - name: make sure the correct hosts file is available
      template: src=templates/hosts dest=/opt/bb/hosts

    - name: make sure the last version of the bigboards software is installed
      apt: name={{ item }} state=latest force=yes
      with_items:
        - bigboards-cli
        - bigboards-mmc

    - name: make sure the right permissions are set on the bigboards directories
      file: path={{item}} owner=bb mode=777 state=directory
      with_items:
        - /var/log/bigboards
        - /var/log/bigboards/tasks

    - name: make sure the bigboards-mmc has been restarted
      service: name=bigboards-mmc state=restarted