#!/bin/bash

function moduleExecute() {
    ansible-playbook ${DIR}/ansible/system/dump/dump.yml

    return $?
}

function commandInfo() {
    echo "      dump            Dump details about this system to a tarball inside your home directory. "
    echo "                      This operation is mainly usefull for debugging purposes."
    echo
}