#!/bin/bash

function moduleExecute() {
    rx='([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'

    if [[ -z $1 || -z $2 ]]; then
        return 1
    fi

    if [[ ! $1 =~ ^$rx\.$rx\.$rx$ ]]; then
        echo "Invalid network range!"
        echo "  expected format: <1-255>.<0-255>.<0-255>"
        return  1
    fi

    if [[ ! $2 =~ ^$rx\.$rx\.$rx\.$rx$ ]]; then
        echo "Invalid network mask!"
        echo "  expected format: <1-255>.<0-255>.<0-255>.<0-255>"
        return 1
    fi

    ansible-playbook ${DIR}/ansible/network/switch_network.yml --extra-vars "network_range=${1} network_mask=${2}"
    return $?
}

function commandInfo() {
    echo "      switch          Change the internal ip addresses of the cluster. "
    echo
    echo "                      ARGUMENTS:"
    echo "                      range       the network range formatted as <1-255>.<0-255>.<0-255>"
    echo "                      mask        the netmask formatted as <1-255>.<0-255>.<0-255>.<0-255>"
    echo
}