---
#- name: be sure host key checking is disabled
#  lineinfile: dest=/etc/ansible/ansible.cfg regexp="host_key_checking " insertafter="^#host_key_checking " line="host_key_checking = False"

- name: be sure the ansible directory exists
  file: state=directory path={{ item }}
  with_items:
    - /etc/ansible
    - /etc/ansible/facts.d

- name: be sure the hosts file holds the nodes
  template: src=etc/hosts dest=/etc/hosts