---
- hosts: host
  sudo: yes
  tasks:
    - name: be sure the correct hex facts are available
      template: src=templates/etc/ansible/facts.d/hex.fact dest=/etc/ansible/facts.d/hex.fact

    - name: be sure the interfaces are configured correctly
      template: src=templates/etc/network/interfaces dest=/etc/network/interfaces
      notify: Restart Network

    - name: be sure docker is installed ( + dependencies )
      apt: name={{ item }} state=latest
      with_items:
        - docker.io
        - python-pip
        - python-dev
        - build-essential

    - name: be sure the requests for python are removed
      file: state=absent path=/usr/local/lib/python2.7/dist-packages/requests

    - name: be sure the docker python bindings are installed
      pip: name=docker-py state=latest

    - name: be sure the docker version is up to date
      copy: src=files/docker-1.3.0 dest=/usr/bin/docker
      notify: Restart Docker

    - name: make sure the bigboards log directory is available
      file: state=directory path=/var/log/bigboards owner=bb mode=666

  handlers:
    - name: Restart Network
      service: name=networking state=restarted

    - name: Restart Serf
      service: name=serf state=restarted

    - name: Restart Docker
      service: name=docker.io state=restarted