---
- hosts: all:!localhost
  sudo: yes
  tasks:
    - name: make sure the correct kernel is being used
      apt: name="linux-image-extra-{{ansible_kernel}}" state=latest

    - name: make sure the docker data directory exists
      file:
        state: 'directory'
        path: '/data/docker'
        owner: 'bb'
        mode: '777'

    - name: make sure docker is using the correct backend storage
      copy:
        src: 'files/docker.io'
        dest: '/etc/default/docker.io'