---
- name: get the list of containers
  shell: lxc-ls
  register: lxc_list
  tags:
    - container

- name: make sure the {{ tintId }} container exists
  shell: lxc-clone -o bb-template -n {{ tintId }}
  when: "'{{ tintId }}' not in '''{{lxc_list.stdout}}'''"
  tags:
    - container

- name: make sure the lxc autostart directory is available
  file: state=directory path=/etc/lxc/auto
  tags:
    - container

- name: make sure the container is started at boot
  file: state=link src=/var/lib/lxc/{{tintId}}/config dest=/etc/lxc/auto/{{tintId}}
  tags:
    - container

- name: make sure the container is started
  shell: lxc-start -d -n {{ tintId }}
  tags:
    - container

- name: wait for the container ({{ansible_local.hex.id}}-v{{ansible_hostname}}) to be started
  wait_for: host={{ansible_local.hex.id}}-v{{ansible_hostname}} port=22