---
- hosts: host
  sudo: yes
  tasks:
    - name: make sure the software is installed
      apt:
        name: "{{ item }}"
        state: "latest"
      with_items:
        - libffi-dev
        - supervisor

    - name: make sure supervisord is running as bb
      lineinfile: dest=/etc/supervisor/supervisord.conf regexp="^user=" insertafter="^[supervisord]$" line="user=bb"

    - name: make sure supervisor is started and will start at boot
      service:
        name: "supervisor"
        state: "started"
        enabled: "yes"

    - name: make sure the avahi-daemon init file is up to date
      template:
        src: "templates/etc/init/avahi-daemon.conf"
        dest: "/etc/init/avahi-daemon.conf"

    - name: make sure the avahi configuration file is up to date
      template:
        src: "templates/etc/avahi/avahi-daemon.conf"
        dest: "/etc/avahi/avahi-daemon.conf"

    - name: make sure avahi is started and will start on boot
      service:
        name: "avahi-daemon"
        state: "running"
        enabled: "yes"

    - name: make sure butterfly is installed
      pip:
        name: "butterfly"
        state: "present"

    - name: make sure the butterfly supervisord file is up to date
      template:
        src: "templates/etc/supervisor/conf.d/butterfly.conf"
        dest: "/etc/supervisor/conf.d/butterfly.conf"

    - name: make sure butterfly is started
      supervisorctl:
        name: "butterfly"
        state: "restarted"