#!/usr/bin/env bash

# -- add the bigboards system user
adduser --system bb

# -- create the bigboards tints directory
sudo -u bb mkdir -p /opt/bb/tints.d

# -- change the rights to the bigboards directory
chown bb -R /opt/bb/runtimes/bigboards-mmc

pushd /opt/bb/runtimes/bigboards-mmc/client
    # -- install the nodejs api dependencies
    npm install

    # -- make sure bower installs all dependencies
    sudo -u bb bower install --config.interactive=false
popd