#!/bin/bash
# -- ----------------------------------------------------------------------- --
# -- bb : BigBoards management script
# -- ----------------------------------------------------------------------- --
ACTION=${1}
PLAYBOOK="ansible-playbook -i /opt/bb/hosts"
DIR=$(dirname "$(readlink -f ${BASH_SOURCE[0]})" )

if [[ $EUID -eq 0 ]];
then
   echo "The BB command may not be run as root"
   exit 1
fi

usage() {
    echo "Usage: $0 [version|network|run|mmc|container|system|help]" 1>&2; exit 1;
}

validateTintBuilder() {
    [ ! -e "~/.tint-builder" ] && echo "Not .tint-builder file found in the home directory of ${USER} " && exit 8;
    source "~/.tint-builder"

    [ -z "${BB_USERNAME}" ] && echo "BB_USERNAME not set" && exit 7;
    [ -z "${BB_EMAIL}" ] && echo "BB_EMAIL not set" && exit 7;
    [ -z "${BB_PASSWORD}" ] && echo "BB_PASSWORD not set" && exit 7;
}

update() {
    sudo apt-get update
    sudo apt-get install -y --force-yes bigboards-updater bigboards-cli bigboards-mmc

    AVAILABLE_PATCHES="$(ls /opt/bb/runtimes/bigboards-updater/patches)"
    CURRENT_VERSION=

    if [ -f /opt/bb/.versions ]
    then
        CURRENT_VERSION="$(tail -n 1 /opt/bb/.versions | cut -d '|' -f1)"
    fi

    for p in $AVAILABLE_PATCHES
    do
        if [ -z "${CURRENT_VERSION}" ] || [ "${p}" -gt "${CURRENT_VERSION}" ]
        then
            echo "Invoking patch ${p}"
            ${PLAYBOOK} /opt/bb/runtimes/bigboards-updater/patches/${p}/install.yml && echo "${p}|$(date)" >> /opt/bb/.versions

            [ "$?" -ne "0" ] && echo "Something went wrong when invoking patch ${p}. Have a look at the output above to figure out what went wrong." && break;
        fi
    done

    sudo service bigboards-mmc restart
}

case "${ACTION}" in
    version)
        case "${2}" in
            switch)
                [ -z "${3}" ] && echo "No target version provided! Please specify this as 3rd parameter ..." && usage

                ${PLAYBOOK} --extra-vars "version=${3}" ${DIR}/ansible/switch_version.yml
                ;;
            update)
                update
                ;;
            *)
                echo "Invalid version action '${2}'"
                usage
                ;;
        esac
        ;;
    network)
        case "${2}" in
            switch)
                # validate the given network prefix
                if [[ ! $3 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
                    echo "Invalid network prefix! please specify a network prefix as xxx.xxx.xxx"
                    exit 3
                fi

                ${PLAYBOOK} --extra-vars "ip_prefix=${3}" ${DIR}/ansible/switch_ip/switch_ip.yml
                ;;
            *)
                echo "Invalid network action '${2}'"
                usage
                ;;
        esac
        ;;
    run)
        ansible host -i /opt/bb/hosts --sudo -m shell -a "$2"
        ;;
    mmc)
        sudo service bigboards-mmc $2
        ;;
    container)
        case "${2}" in
            list)
                sudo docker ps
                ;;
            attach)
                sudo docker exec -it $3 /bin/bash
                ;;
            tail)
                sudo docker logs --tail=100 -f $3
                ;;
            build)
                validateTintBuilder

                ARCH=$(uname -m)
                NAME='${3}'
                VERSION='${4}'
                IMAGE_NAME="${BB_USERNAME}/${NAME}-${ARCH}:${VERSION}"

                echo "Building ${IMAGE_NAME}"
                sudo -E docker build -t ${IMAGE_NAME} ${5}

                echo "Logging into the docker hub"
                docker login -e $BB_EMAIL} -u ${BB_USERNAME} -p ${BB_PASSWORD}

                echo "Pushing ${IMAGE_NAME}"
                sudo -E docker push ${IMAGE_NAME}
                ;;
            *)
                echo "Invalid switch action '${2}'"
                usage
                ;;
        esac
        ;;
    system)
        case "${2}" in
            purge)
                ${PLAYBOOK} ${DIR}/ansible/system/purge.yml
                ;;
            *)
                echo "Invalid switch action '${2}'"
                usage
                ;;
        esac
        ;;
    help)
        usage
        ;;
    *)
        echo "Invalid action '$ACTION'"
        usage
        ;;
esac
