---

## -- Enable forwarding and masquerading
- name: be sure Ipv4 forwarding is 
  lineinfile: dest=/etc/sysctl.conf regexp='^net.ipv4.ip_forward=' line='net.ipv4.ip_forward=1'
  tags:
    - config
    - network
    - nat

- name: be sure the iptables script is available
  copy: src=etc/iptables.sav dest=/etc/iptables.sav
  tags:
    - config
    - network
    - nat

- name: be sure the iptables rules are up to date
  shell: iptables-restore < /etc/iptables.sav
  tags:
    - config
    - network
    - nat

- name: be sure iptables is configured to load on the end of the runlevel
  copy: src=etc/rc.local dest=/etc/rc.local
  tags:
    - config
    - network
    - nat

- name: be sure the nginx repository has been installed
  apt_repository: repo="ppa:nginx/"{{ item }} state=absent update_cache=yes
  with_items:
    - stable
    - development
  tags:
    - network

- name: be sure nginx is installed
  apt: name=nginx state=latest force=yes
  tags:
    - network

- name: be sure the nginx configuration files are up to date
  template: src=etc/nginx/conf.d/default.conf dest=/etc/nginx/conf.d/default.conf mode=755
  notify: Restart nginx
  tags:
    - network
    - config

- name: be sure the bigboards home directory has the right structure
  file: state=directory owner=bb group=bigboards path={{item}}
  with_items:
    - /opt/bb/runtimes
    - /opt/bb/tints.d

- name: be sure the bigboards management console is installed
  apt: state=latest name={{item}} force=yes update_cache=yes
  with_items:
    - bigboards-mmc

- name: preinitialize the hex
  lineinfile: "dest=/opt/bb/hex.yml regexp='^initialized:' line='initialized: true'"

- name: be sure the ansible hosts configuration is available
  copy: src=hosts dest=/opt/bb/hosts mode=0666 owner=bb group=bigboards
  tags:
    - mmc

