---
- hosts: host-coordinators
  sudo: yes
  tasks:
    name: Install ganglia server (Ubuntu)
      apt: pkg={{item}} state=latest
      with_items:
        - ganglia-webfrontend
        - gmetad

    - name: Create the ganglia data directory
      file: state=directory path={{item}}
      with_items:
        - "/data/ganglia"
        - "/data/ganglia/rrds"

    - name: Configure apache link (conf-available)
      file: src=/etc/ganglia-webfrontend/apache.conf dest=/etc/apache2/conf-available/ganglia.conf state=link
      notify: restart apache

    - name: Configure apache link (conf-enabled)
      file: src=/etc/apache2/conf-available/ganglia.conf dest=/etc/apache2/conf-enabled/ganglia.conf state=link
      notify: restart apache

    - name: Configure gmetad
      template: src=templates/gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf
      notify: restart gmetad

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    # gmetad and ganglia-monitor init scripts does not support `status`
    # argument.
    - name: restart gmetad
      command: service gmetad restart
      when: '"ganglia_master" in group_names'

- hosts: host
  sudo: yes
  tasks:
    - name: Install ganglia monitor
      apt: pkg=ganglia-monitor state=latest

    - name: Configure gmond
      template: src=templates/gmond.conf.j2 dest=/etc/ganglia/gmond.conf
      notify: restart gmond

  handlers:
    - name: restart gmond
      command: service ganglia-monitor restart