---
# This playbook deploys the AWX application (database, web and worker) to a
# single server.

- hosts: host
  sudo: yes
  roles:
    - bb-backup
    - fix-debootstrap
    - ntp
    - bb-common

- hosts: host-coordinators
  sudo: yes
  roles:
    - bb-host-common
    - bb-host-coordinator

- hosts: host-workers
  sudo: yes
  roles:
    - bb-host-common
    - bb-host-worker

- hosts: host
  sudo: yes
  roles:
    - bb-restore