---
- hosts: local
  tasks:
    - name: be sure the tint directory exists
      file: state=directory path=/opt/bb/tints.d/stack

    - name: be sure the tint sources are available
      git: repo={{ tint.uri }} dest={{ tint.path }}

###############################################################################
##
## Structure
##
###############################################################################

    - name: remove the work directory so we can start with a clean slate
      command: rm -rf {{ tint.path }}/work removes={{ tint.path }}/work

    - name: be sure the directory structure for the tint playbook has been created
      file:
        state: "directory"
        path: "{{ item }}"
      with_items:
        - "{{ tint.path }}/work"
        - "{{ tint.path }}/work/roles"
        - "{{ tint.path }}/work/group_vars"

###############################################################################
##
## Inventory
##
###############################################################################

    - name: create the group_vars file
      template:
        src: "group_vars_all.j2"
        dest: "{{ tint.path }}/work/group_vars/all"

    - name: create the hosts file
      template:
        src: "hosts.j2"
        dest: "{{ tint.path }}/work/_hosts"

###############################################################################
##
## Playbooks
##
###############################################################################

    - name: create the install playbook
      template:
        src: "install.yml.j2"
        dest: "{{ tint.path }}/work/_install.yml"

    - name: create the uninstall playbook
      template:
        src: "uninstall.yml.j2"
        dest: "{{ tint.path }}/work/_uninstall.yml"


###############################################################################
##
## Roles
##
###############################################################################

    - file:
        state: "directory"
        path: "{{ tint.path }}/work/roles/{{ item.name }}"
      with_items: tint.stack.containers

    - file:
        state: "directory"
        path: "{{ tint.path }}/work/roles/{{ item.name }}/tasks"
      with_items: tint.stack.containers

    - file:
        state: "directory"
        path: "{{ tint.path }}/work/roles/{{ item.name }}/files"
      with_items: tint.stack.containers

    - name: create the role install task file
      template:
        src: "docker-init.conf.j2"
        dest: "{{ tint.path }}/work/roles/{{ item.name }}/files/{{ item.name }}.conf"
      with_items: tint.stack.containers

    - name: create the role main task file
      template:
        src: "role_main.yml.j2"
        dest: "{{ tint.path }}/work/roles/{{ item.name }}/tasks/main.yml"
      with_items: tint.stack.containers

    - name: create the role install task file
      template:
        src: "role_install.yml.j2"
        dest: "{{ tint.path }}/work/roles/{{ item.name }}/tasks/install.yml"
      with_items: tint.stack.containers

    - name: create the role uninstall task file
      template:
        src: "role_uninstall.yml.j2"
        dest: "{{ tint.path }}/work/roles/{{ item.name }}/tasks/uninstall.yml"
      with_items: tint.stack.containers

    - stat:
        path: "{{ tint.path }}/config/all/"
      register: st

    - name: copy the general configuration templates from the tint to the work directory
      copy:
        src: "{{ tint.path }}/config/all/"
        dest: "{{ tint.path }}/work/roles/{{ item.name }}/templates"
      with_items: tint.stack.containers
      when: st.stat.exists == True

    - stat:
        path: "{{ tint.path }}/config/{{ item.name }}/"
      register: role_config
      with_items: tint.stack.containers

    - name: copy the configuration templates from the tint to the work directory
      copy:
        src: "{{ tint.path }}/config/{{ item.item.name }}/"
        dest: "{{ tint.path }}/work/roles/{{ item.item.name }}/templates/"
      when: item.stat.exists
      with_items: role_config.results

    - name: be sure the directory structure for the tint playbook has been created
      file:
        state: "directory"
        recurse: "yes"
        path: "{{ tint.path }}"
        owner: "bb"