---
- hosts: local
  sudo: yes
  tasks:
    - name: be sure the tint directory exists
      file: state=directory path=/opt/bb/tints.d/tutor

    - name: be sure the tint sources are available
      git: repo={{ tint.uri }} dest={{ tint.path }}

    - name: be sure the directory structure for the tint playbook has been created
      file:
        state: "directory"
        recurse: "yes"
        path: "{{ tint.path }}"
        owner: "bb"
        group: "bigboards"