#!/bin/sh

. /etc/default/serf

# exit if not ipv4
[ "$ADDRFAM" != "inet" ] && exit 0
[ "$IFACE" != "$INT_IFACE" ] && [ "$IFACE" != "$EXT_IFACE" ] && exit 0

# get the ip address of the interface
IFCFG="ifconfig $INT_IFACE"
IP=$($IFCFG | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
BCAST=$($IFCFG | grep 'Bcast:' | awk '{ print $3}' | cut -d: -f2)
MASK=$($IFCFG | grep 'Mask:' | awk '{ print $4}' | cut -d: -f2)
MAC=$($IFCFG | grep 'HWaddr ' |  awk '{ print $5}')

# update the tag for the network interface on the serf agent
/opt/serf/bin/serf tags \
    -set network.$IFACE.ip=$IP
    -set network.$IFACE.mac=$MAC
    -set network.$IFACE.netmask=$MASK
    -set network.$IFACE.broadcast=$BCAST
