---
- hosts: host
  sudo: yes
  tasks:
    - name: get the list of containers
      shell: lxc-ls
      register: lxc_list

    - name: be sure the containers are stopped
      shell: lxc-stop -n {{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}
      ignore_errors: true
      when: "'{{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}' in '''{{lxc_list.stdout}}'''"

    - name: update the network configuration on all nodes
      template: src=interfaces dest=/etc/network/interfaces owner=root group=root

- hosts: host-coordinators
  sudo: yes
  tasks:
    - name: add an ip alias
      shell: ip addr add {{ip_prefix}}.1/24 dev br1

- hosts: host-workers
  sudo: yes
  tasks:
    - name: restart the network
      service: name=networking state=restarted
      async: 30
      poll: 0

- hosts: local
  sudo: yes
  tasks:
    - name: restart the network
      service: name=networking state=restarted
    - name: update the hosts file for the nodes and remove the old addresses
      template: src=hosts dest=/etc/hosts owner=root group=root
    - name: update the hosts file for the containers and remove the old addresses
      template: src=hosts dest=/var/lib/lxc/{{item}}/rootfs/etc/hosts owner=root group=root
      with_items: lxc_list.stdout
    - name: restart the serf agent
      service: name=serf state=restarted

- hosts: host
  sudo: yes
  tasks:
    - name: be sure the containers are started again
      shell: lxc-start -d -n {{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}
      when: "'{{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}' in '''{{lxc_list.stdout}}'''"

- hosts: host-workers
  sudo: yes
  tasks:
    - name: join the master node again
      shell: serf join {{ ansible_local.hex.name }}-n1