---
- hosts: host
  sudo: yes
  tasks:
    - name: get the list of containers
      shell: lxc-ls
      register: lxc_list

    - name: stop the serf daemon
      service: name=serf state=stopped

    - name: be sure the containers are stopped
      shell: lxc-stop -n {{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}
      ignore_errors: true
      when: "'{{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}' in '''{{lxc_list.stdout}}'''"

    - name: update the hosts file for the nodes with the new addresses
      lineinfile: dest=/etc/hosts regexp='^{{ item.ip }}' line='{{ item.ip }} {{ item.name }}' owner=root group=root mode=0644
      with_items:
        - { ip: "{{ip_prefix}}.1", name: "{{ ansible_local.hex.name }}-n1" }
        - { ip: "{{ip_prefix}}.2", name: "{{ ansible_local.hex.name }}-n2" }
        - { ip: "{{ip_prefix}}.3", name: "{{ ansible_local.hex.name }}-n3" }
        - { ip: "{{ip_prefix}}.4", name: "{{ ansible_local.hex.name }}-n4" }
        - { ip: "{{ip_prefix}}.5", name: "{{ ansible_local.hex.name }}-n5" }
        - { ip: "{{ip_prefix}}.6", name: "{{ ansible_local.hex.name }}-n6" }
        - { ip: "{{ip_prefix}}.11", name: "{{ ansible_local.hex.name }}-v1" }
        - { ip: "{{ip_prefix}}.12", name: "{{ ansible_local.hex.name }}-v2" }
        - { ip: "{{ip_prefix}}.13", name: "{{ ansible_local.hex.name }}-v3" }
        - { ip: "{{ip_prefix}}.14", name: "{{ ansible_local.hex.name }}-v4" }
        - { ip: "{{ip_prefix}}.15", name: "{{ ansible_local.hex.name }}-v5" }
        - { ip: "{{ip_prefix}}.16", name: "{{ ansible_local.hex.name }}-v6" }

    - name: update the network configuration on all nodes
      template: src=interfaces dest=/etc/network/interfaces owner=root group=root

    - name: update the hosts file for the nodes and remove the old addresses
      template: src=hosts dest=/etc/hosts owner=root group=root

    - name: update the hosts file for the containers and remove the old addresses
      template: src=hosts dest=/var/lib/lxc/{{item}}/rootfs/etc/hosts owner=root group=root
      with_items: lxc_list

    - name: restart the network
      shell: ifdown br1 && ifup br1

    - name: be sure the containers are started again
      shell: lxc-start -d -n {{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}
      when: "'{{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}' in '''{{lxc_list.stdout}}'''"

    - name: start the serf daemons again
      service: name=serf state=started