---
- hosts: host-coordinators
  sudo: yes
  roles:
    - bb-backup

- hosts: host
  sudo: yes
  roles:
    - fix-debootstrap
    - ntp
    - bb-common

- hosts: host-coordinators
  sudo: yes
  roles:
    - bb-host-common
    - bb-host-coordinator

- hosts: host-workers
  sudo: yes
  roles:
    - bb-host-common
    - bb-host-worker

- hosts: host-coordinators
  sudo: yes
  roles:
    - bb-restore