---
- hosts: host
  sudo: yes
  tasks:
    - name: be sure git is installed
      apt: state=latest name=git

    - name: be sure bower is installed
      npm: name=bower global=yes

    - name: be sure node and nodejs are pointing to the same command
      file: state=link src=/usr/bin/nodejs dest=/usr/bin/node

    - name: be sure the serf directory structure is available
      file: state=directory name={{item}}
      with_items:
        - /opt/serf
        - /opt/serf/bin
        - /opt/serf/events.d

    - name: be sure the serf for ARM binary is available
      copy: src=opt/serf/bin/serf dest=/opt/serf/bin/serf

    - name: be sure the serf init script is installed
      copy: src=etc/init/serf.conf dest=/etc/init/serf.conf

    - name: be sure the serf init configuration is installed
      copy: src=etc/default/serf dest=/etc/default/serf

- hosts: host-coordinators
  sudo: yes
  tasks:
    - name: be sure the bigboards management console is installed
      apt: state=latest name={{item}} force=yes update_cache=yes
      with_items:
        - bigboards-mmc
      notify: Restart BigBoards Management Console
  handlers:
    - name: Restart BigBoards Management Console
      service: state=restarted name=bigboards-mmc

- hosts: host
  sudo: yes
  tasks:
    - name: be sure the harddisk is initialized
      shell: creates=/dev/sda1 parted /dev/sda mklabel msdos mkpart primary 0% 100%

    - name: be sure the harddrive filesystem has been created
      shell: creates=/root/.sda1.initialized mkfs.ext4 /dev/sda1 && touch /root/.sda1.initialized

    - name: be sure the data mountpoint exists
      file: state=directory path=/data owner=bb group=bigboards

    - name: be sure the correct FSTAB file is installed
      copy: src=files/etc/fstab dest=/etc/fstab

    - name: be sure the data directory is mounted
      shell: creates=/data/lost+found mount /data

    - name: be sure bower is installed
      npm: name=bower global=yes

    - name: be sure the bigboards node is installed
      apt: state=latest name=bigboards-node force=yes update_cache=yes
      notify: Restart BigBoards Node

  handlers:
    - name: Restart BigBoards Node
      service: state=restarted name=bigboards-node