---
- hosts: host
  sudo: yes
  tasks:
    - name: be sure host key checking is disabled
      lineinfile: dest=/etc/ansible/ansible.cfg regexp="host_key_checking " insertafter="^#host_key_checking " line="host_key_checking = False"

    - name: be sure the hosts file holds the nodes and containers
      template: src=templates/etc/hosts dest=/etc/hosts

    - name: be sure the serf configuration file is available
      template: src=templates/etc/serf/serf.conf dest=/etc/serf/serf.conf
      notify: Restart Serf

    - name: be sure the harddisk is initialized
      shell: creates=/dev/sda1 parted /dev/sda mklabel msdos mkpart primary 0% 100%

    - name: be sure the harddrive filesystem has been created
      shell: creates=/root/.sda1.initialized mkfs.ext4 /dev/sda1 && touch /root/.sda1.initialized

    - name: be sure the data mountpoint exists
      file: state=directory path=/data owner=bb group=bigboards

    - name: be sure the correct FSTAB file is installed
      copy: src=files/etc/fstab dest=/etc/fstab

    - name: be sure the data directory is mounted
      shell: creates=/data/lost+found mount /data

    - name: be sure the bigboards node is installed
      apt: state=latest name=bigboards-node force=yes update_cache=yes
      notify: Restart BigBoards Node

    - name: be sure the data disk is mounted in the containers
      lineinfile: dest=/var/lib/lxc/{{ ansible_local.hex.name }}-v{{ ansible_local.hex.node.sequence }}/ regexp="/data " insertafter="^/opt/bb " line="/data  data  none  bind  0 0"

  handlers:
    - name: Restart BigBoards Node
      service: state=restarted name=bigboards-node
    - name: Restart Serf
      service: state=restarted name=serf


- hosts: host-coordinators
  sudo: yes
  tasks:
    - name: be sure the bigboards management console is installed
      apt: state=latest name={{item}} force=yes update_cache=yes
      with_items:
        - bigboards-mmc
      notify: Restart BigBoards Management Console

    - name: be sure the ansible hex facts are writable by the mmc
      file: path=/etc/ansible/facts.d/hex.fact state=file mode=774
  handlers:
    - name: Restart BigBoards Management Console
      service: state=restarted name=bigboards-mmc