---
- hosts: host-coordinators
  sudo: yes
  tasks:
    - name: be sure the bigboards management console is installed
      apt: state=latest name={{item}} force=yes update_cache=yes
      with_items:
        - bigboards-mmc
      notify: Restart BigBoards Management Console
  handlers:
    - name: Restart BigBoards Management Console
      service: state=restarted name=bigboards-mmc

- hosts: host
  sudo: yes
  tasks:
    - name: be sure the bigboards-node configuration file is available
      template: src=templates/hex-node.yml dest=/opt/bb/hex-node.yml owner=bb group=bigboards
      notify: Restart BigBoards Node

    - name: be sure the harddisk is initialized
      shell: creates=/dev/sda1 parted /dev/sda mklabel msdos mkpart primary 0% 100%

    - name: be sure the harddrive filesystem has been created
      shell: creates=/root/.sda1.initialized mkfs.ext4 /dev/sda1 && touch /root/.sda1.initialized

    - name: be sure the data mountpoint exists
      file: state=directory path=/data owner=bb group=bigboards

    - name: be sure the correct FSTAB file is installed
      copy: src=files/etc/fstab dest=/etc/fstab

    - name: be sure the data directory is mounted
      shell: creates=/data/lost+found mount /data

  handlers:
    - name: Restart BigBoards Node
      service: state=restarted name=bigboards-node