#!/bin/bash

function update_ip() {
    DEVICE_NAME=$1
    NODE_NAME=$(hostname)
    NODE_SEQ=$2
    IP=$3

    TMPFILE=$(mktemp /tmp/temporary-file.XXXXXXXX)

    cat > ${TMPFILE} << EOF
{
  "ip": "${IP}",
  "sequence": ${NODE_SEQ},
  "hostname": "${NODE_NAME}"
}
EOF

    URL="http://api.hive.bigboards.io/api/v1/devices/${DEVICE_NAME}/nodes/${NODE_NAME}"

    # Update the Hosted Zone record
    curl -H 'Content-Type: application/json' -X PUT -d '@${TMPFILE}' $URL
}

# update_ip hex_name node_seq ip
IFCFG="ifconfig eth1"
IP=$($IFCFG | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
NODE_SEQ=$(echo `ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'` | rev | cut -d '.' -f 1)
DEVICE_NAME=$(hostname |cut -d '-' -f 1)

update_ip $DEVICE_NAME $NODE_SEQ $IP
