## Docker 1.10 ################################################################
# There is a very nasty bug in the current version of docker we were using. The
# only solution seems to be to upgrade docker to a new version. This fix is
# only applied on x86 machines since upgrading docker on the armv7's requires
# a distro upgrade.
- hosts: host
  sudo: yes
  tasks:
    - name: make sure the apt http driver is installed
      when: ansible_machine == 'x86_64'
      apt: name=apt-transport-https state=present force=yes

    - name: make sure all docker daemons are stopped
      when: ansible_machine == 'x86_64'
      service: name=docker state=stopped

    - name: uninstall the current docker version
      when: ansible_machine == 'x86_64'
      apt: name=docker.io state=absent

    - name: add the docker apt repository key (without proxy)
      when: ansible_machine == 'x86_64' and ansible_env.http_proxy is not defined
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

    - name: add the docker apt repository key (with proxy)
      when: ansible_machine == 'x86_64' and ansible_env.http_proxy is defined
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
      environment:
          http_proxy: $http_proxy
          https_proxy: $https_proxy

    - name: add the docker apt repository
      when: ansible_machine == 'x86_64'
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

    - name: install the new docker version
      when: ansible_machine == 'x86_64'
      apt: name=docker-engine update_cache=yes state=present

    - name: configure the docker daemon
      when: ansible_machine == 'x86_64'
      lineinfile: dest=/etc/default/docker regexp=^DOCKER_OPTS= line="DOCKER_OPTS=\"-s aufs -g /data/docker/data -D\""

    - name: add the bb user to the docker group
      when: ansible_machine == 'x86_64'
      user: name=bb groups=docker append=yes

    - name: make sure the docker service is started again
      service: name=docker state=started