---
- hosts: host
  sudo: yes
  tasks:
    - name: be sure the lxc bb-template container is removed
      shell: lxc-destroy -f -n {{item}} removes=/var/lib/lxc/{{item}}
      ignore_errors: yes
      with_items:
        - 'bb-template'
        - '{{ ansible_local.bb.hex.name }}-v{{ ansible_local.bb.node.sequence }}'
