## ####################################################################################################################
## CLEAN UP
## ####################################################################################################################
- hosts: host
  sudo: yes
  tasks:
    - name: be sure the lxc bb-template container is removed
      shell: lxc-destroy -f -n {{item}} removes=/var/lib/lxc/{{item}}
      ignore_errors: yes
      with_items:
        - 'bb-template'
        - '{{ ansible_local.bb.hex.name }}-v{{ ansible_local.bb.node.sequence }}'

    - name: be sure existing tints are uninstalled
      file:
        path: '{{ item }}'
        state: 'absent'
      with_items:
        - /opt/bb/tints.d/stack/
        - /opt/bb/tints.d/dataset/
        - /opt/bb/tints.d/tutor/

    - name: be sure the ansible hex facts are writable by the mmc
      file:
        path: '/etc/ansible/facts.d/hex.fact'
        state: 'absent'

## ####################################################################################################################
## NETWORK
## ####################################################################################################################
- hosts: host
  sudo: yes
  tasks:
    - name: be sure the interfaces are configured correctly
      template:
        src: 'templates/{{ item }}'
        dest: '/{{ item }}'
      with_items:
        - 'etc/network/interfaces'
        - 'etc/dhcp/dhclient.conf'
        - 'etc/resolv.conf'
      notify: Restart Network

  handlers:
    - name: Restart Network
      command: bash -c "ifdown {{ item }} && ifup {{ item }}"
      when: item != 'lo'
      with_items: ansible_interfaces

## ####################################################################################################################
## ANSIBLE
## ####################################################################################################################
- hosts: host-coordinators
  sudo: yes
  tasks:
    - name: make sure the correct hosts file is available
      template:
        src: 'templates/opt/bb/hosts'
        dest: '/opt/bb/hosts'

    - name: make sure the ansible ppa is installed
      apt_repository:
        repo: "ppa:ansible/ansible"

    - name: make sure ansible is up to date
      apt:
        name: "ansible"
        state: "latest"