- shell: mount | grep " /data " | cut -d ' ' -f1
  register: data_dev

- shell: mount | grep " / " | cut -d ' ' -f1
  register: root_dev

- mount:
    name: "/data"
    src: "{{ data_dev.stdout }}"
    state: "unmounted"
  when: '"/dev/" in data_dev.stdout and root_dev.stdout != data_dev.stdout'

- shell: rm -rf /data/*

- mount:
    name: "/data"
    src: "{{ data_dev.stdout }}"
    state: "absent"
  when: '"/dev/" in data_dev.stdout and root_dev.stdout != data_dev.stdout'