- hosts: host
  become: yes
  become_user: root
  tasks:
    - name: make sure the apt configuration file exists
      file: path=/etc/apt/apt.conf state=touch

    - name: set apt proxy settings for HTTP
      lineinfile: dest="/etc/apt/apt.conf" regexp="^Acquire::http::proxy.*" line="Acquire::http::proxy \"http://{{ http_proxy_host }}:{{ http_proxy_port }}/\";"

    - name: set apt proxy settings for HTTPS
      lineinfile: dest="/etc/apt/apt.conf" regexp="^Acquire::https::proxy.*" line="Acquire::https::proxy \"http://{{ https_proxy_host }}:{{ https_proxy_port }}/\";"

    - name: set system proxy settings for HTTP
      lineinfile: dest="/etc/environment" regexp="^http_proxy=.*" line="http_proxy=\"http://{{ http_proxy_host }}:{{ http_proxy_port }}/\""

    - name: set system proxy settings for HTTPS
      lineinfile: dest="/etc/environment" regexp="^https_proxy=.*" line="https_proxy=\"http://{{ https_proxy_host }}:{{ https_proxy_port }}/\""

    - name: set the nodejs proxy settings for HTTP
      shell: npm config set proxy http://{{http_proxy_host}}:{{http_proxy_port}}

    - name: set the nodejs proxy settings for HTTPS
      shell: npm config set https-proxy http://{{https_proxy_host}}:{{https_proxy_port}}

    - name: set docker proxy settings for HTTP
      lineinfile: dest="/etc/default/docker" regexp="^export http_proxy=.*" line="export http_proxy=\"http://{{ http_proxy_host }}:{{ http_proxy_port }}/\""

    - name: set docker proxy settings for HTTPS
      lineinfile: dest="/etc/default/docker" regexp="^export https_proxy=.*" line="export https_proxy=\"http://{{ https_proxy_host }}:{{ https_proxy_port }}/\""

    - name: set git proxy settings for HTTP
      shell: git config --global http.proxy http://{{http_proxy_host}}:{{http_proxy_port}}

    - name: set git proxy settings for HTTPS
      shell: git config --global https.proxy http://{{https_proxy_host}}:{{https_proxy_port}}

    - name: set git proxy settings for HTTP
      shell: git config --system http.proxy http://{{http_proxy_host}}:{{http_proxy_port}}

    - name: set git proxy settings for HTTPS
      shell: git config --system https.proxy http://{{https_proxy_host}}:{{https_proxy_port}}

    - name: set bb.fact proxy settings for HTTP
      lineinfile: dest="/etc/ansible/facts.d/bb.fact" regexp="^http_proxy=.*" insertafter="^\[network\]" line="http_proxy=http://{{ http_proxy_host }}:{{ http_proxy_port }}/"

    - name: set bb.fact proxy settings for HTTPS
      lineinfile: dest="/etc/ansible/facts.d/bb.fact" regexp="^https_proxy=.*" insertafter="^\[network\]" line="https_proxy=http://{{ https_proxy_host }}:{{ https_proxy_port }}/"

- hosts: host-coordinators
  become: yes
  become_user: root
  tasks:
    - name: set bigboards-mmc proxy settings for HTTP
      lineinfile:
        dest: "/etc/init/bigboards-mmc.conf"
        regexp: "^env http_proxy=.*"
        insertafter: "^env BB_ENVIRONMENT="
        line: "env http_proxy=\"http://{{ http_proxy_host }}:{{ http_proxy_port }}/\""

    - name: set bigboards-mmc proxy settings for HTTPS
      lineinfile:
        dest: "/etc/init/bigboards-mmc.conf"
        regexp: "^env https_proxy=.*"
        insertafter: "^env BB_ENVIRONMENT="
        line: "env https_proxy=\"http://{{ https_proxy_host }}:{{ https_proxy_port }}/\""

    - name: make sure .bowerrc exists
      copy:
        dest: "/opt/bb/runtimes/bigboards-mmc/client/.bowerrc"
        content: "{\n\"dummy\": \"value\"\n}"
        force: "no"
        owner: "bb"
        group: "root"
        mode: "u=rw,g=r,o=r"

    - name: set .bowerrc proxy settings for HTTP
      lineinfile:
        dest: "/opt/bb/runtimes/bigboards-mmc/client/.bowerrc"
        regexp: "^\"proxy\":.*"
        insertafter: "^{$"
        line: "\"proxy\": \"http://{{ http_proxy_host }}:{{ http_proxy_port }}/\", "

    - name: set .bowerrc proxy settings for HTTPS
      lineinfile:
        dest: "/opt/bb/runtimes/bigboards-mmc/client/.bowerrc"
        regexp: "^\"https-proxy\":.*"
        insertafter: "^{$"
        line: "\"https-proxy\": \"http://{{ https_proxy_host }}:{{ https_proxy_port }}/\", "
