---
- name: "ensure /etc/bigboards/ssl folders are present"
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "root"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { path: "/etc/bigboards/ssl", group: "root", mode: "u=rwx,g=rx,o=rx" }
    - { path: "/etc/bigboards/ssl/certs", group: "root", mode: "u=rwx,g=rx,o=rx" }
    - { path: "/etc/bigboards/ssl/private", group: "ssl-cert", mode: "u=rwx,g=x,o=" }

- name: "install bigboards-mmc snakeoil certs"
  file:
    path: "/etc/bigboards/ssl/certs/ssl-cert-bigboards-mmc.pem"
    state: "link"
    src: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"

- name: "install bigboards-mmc snakeoil key"
  file:
    path: "/etc/bigboards/ssl/private/ssl-cert-bigboards-mmc.key"
    state: "link"
    src: "/etc/ssl/private/ssl-cert-snakeoil.key"
    owner: "root"
    group: "ssl-cert"
    mode: "u=rw,g=r,o="

- name: "install auth modules"
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "libapache2-mod-authnz-external"
    - "libapache2-mod-authz-unixgroup"
    - "pwauth"

- name: "disable some defaults"
  file:
    path: "/etc/apache2/sites-enabled/{{ item }}"
    state: "absent"
    src: "/etc/apache2/sites-available/{{ item }}"
    owner: "root"
    group: "root"
    mode: "u+rw,g=r,o=r"
  with_items:
    - "000-default.conf"
    - "default-ssl.conf"
  notify: "restart apache2"

- name: "only highly secure ciphers"
  lineinfile:
    dest: "/etc/apache2/mods-available/ssl.conf"
    regexp: "^[ \t]SSLCipherSuite"
    line: "\tSSLCipherSuite HIGH:!aNULL:!MD5"
  notify: "restart apache2"

- name: "install authz_external_pwauth.conf"
  template:
    src: "templates/etc/apache2/mods-available/authnz_external_pwauth.conf"
    dest: "/etc/apache2/mods-available/authnz_external_pwauth.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  notify: "restart apache2"

- name: "install alternative confs"
  template:
    src: "templates/etc/apache2/sites-available/{{ item }}"
    dest: "/etc/apache2/sites-available/{{ item }}"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  with_items:
    - "redirect-https.conf"
    - "bigboards-mmc.conf"
  notify: "restart apache2"

- name: "enable mods on apache2"
  file:
    path: "/etc/apache2/mods-enabled/{{ item }}"
    state: "link"
    src: "/etc/apache2/mods-available/{{ item }}"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  with_items:
    - "socache_shmcb.load"
    - "ssl.load"
    - "ssl.conf"
    - "authnz_external.load"
    - "authz_unixgroup.load"
    - "authnz_external_pwauth.conf"
    - "proxy.load"
    - "proxy_http.load"
    - "proxy_wstunnel.load"
    - "rewrite.load"
    - "ldap.load"
    - "authnz_ldap.load"
  notify: "restart apache2"

- name: "enable alternatives"
  file:
    path: "/etc/apache2/sites-enabled/{{ item }}"
    state: "link"
    src: "/etc/apache2/sites-available/{{ item }}"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  with_items:
    - "redirect-https.conf"
    - "bigboards-mmc.conf"
  notify: "restart apache2"
