- debug:
    var: 'ansible_local.bb.network.http_proxy'

- name: install dependencies
  apt:
    name: "{{ item}}"
    state: "present"
  with_items:
    - "python-pip"
    - "python-dev"
    - "python-setuptools"
    - "build-essential"
    - "apt-transport-https"
    - "libffi-dev"
    - "libssl-dev"
    - "supervisor"
    - "curl"
    - "gnupg-curl"

- name: correct version of the urllib is installed [NON-PROXY]
  when: ansible_local.bb.network.http_proxy is not defined
  pip:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "urllib3"
    - "pyopenssl"
    - "ndg-httpsclient"
    - "pyasn1"

- name: correct version of the urllib is installed [PROXY]
  when: ansible_local.bb.network.http_proxy is defined
  shell: pip install --proxy {{ansible_local.bb.network.http_proxy}} {{ item }}
  with_items:
    - "urllib3"
    - "pyopenssl"
    - "ndg-httpsclient"
    - "pyasn1"
