- debug:
    var: 'ansible_local.bb.network.http_proxy'

- name: install python tools
  apt:
    name: "{{ item}}"
    state: "present"
  with_items:
    - "python-pip"
    - "python-dev"
    - "python-setuptools"

- name: first update python-setuptools via pip [NON-PROXY]
  when: ansible_local.bb.network.http_proxy is not defined
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "setuptools"

- name: first update python-setuptools via pip [PROXY]
  when: ansible_local.bb.network.http_proxy is defined
  shell: pip install --proxy {{ansible_local.bb.network.http_proxy}} {{ item }} --upgrade
  with_items:
    - "setuptools"

- name: install build utilities
  apt:
    name: "{{ item}}"
    state: "present"
  with_items:
    - "build-essential"
    - "apt-transport-https"
    - "libffi-dev"
    - "libssl-dev"
    - "supervisor"
    - "curl"
    - "gnupg-curl"

- name: install python urllib and security tools installed [NON-PROXY]
  when: ansible_local.bb.network.http_proxy is not defined
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "urllib3"
    - "pyopenssl"
    - "ndg-httpsclient"
    - "pyasn1"

- name: install python urllib and security tools installed [PROXY]
  when: ansible_local.bb.network.http_proxy is defined
  shell: pip install --proxy {{ansible_local.bb.network.http_proxy}} {{ item }} --upgrade
  with_items:
    - "urllib3"
    - "pyopenssl"
    - "ndg-httpsclient"
    - "pyasn1"
