- name: make sure docker can reach its depending libraries
  file:
    src: "/lib/arm-linux-gnueabihf/libdevmapper.so.1.02.1"
    dest: "/lib/arm-linux-gnueabihf/libdevmapper.so.1.02"
    state: "link"

- name: make sure hypriot apt-key is installed
  apt_key:
    url: "https://packagecloud.io/Hypriot/Schatzkiste/gpgkey"
    state: "present"

- name: make sure hypriot apt-repository is installed
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  with_items:
    - "deb https://packagecloud.io/Hypriot/Schatzkiste/ubuntu/ trusty main"
    - "deb-src https://packagecloud.io/Hypriot/Schatzkiste/ubuntu/ trusty main"

- name: install docker-hypriot
  apt:
    name: "docker-hypriot=1.10.3-*"
    update_cache: "yes"
    state: "present"
  notify: "Restart Docker"