- name: Install ganglia server (Ubuntu)
  apt: pkg={{item}} state=latest
  with_items:
    - ganglia-webfrontend
    - gmetad

- name: Create the ganglia data directory
  file: state=directory path={{item}} owner=nobody group=ganglia mode=777
  with_items:
    - "/data/ganglia"
    - "/data/ganglia/rrds"

- name: Configure apache link (conf-available)
  file: src=/etc/ganglia-webfrontend/apache.conf dest=/etc/apache2/conf-available/ganglia.conf state=link
  notify: restart apache

- name: Configure apache link (conf-enabled)
  file: src=/etc/apache2/conf-available/ganglia.conf dest=/etc/apache2/conf-enabled/ganglia.conf state=link
  notify: restart apache

- name: Configure gmetad
  template: src=templates/gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf
  notify: restart gmetad

- name: Configure webfrontend
  copy: src=files/etc/ganglia-webfrontend/conf.php dest=/etc/ganglia-webfrontend/conf.php owner=root group=root mode=644
  notify: restart apache