## ####################################################################################################################
## ANSIBLE
## ####################################################################################################################
- hosts: host-coordinators
  become: yes
  tasks:
    - name: be sure host key checking is disabled
      lineinfile:
        dest: '/etc/ansible/ansible.cfg'
        regexp: 'host_key_checking '
        insertafter: '^#host_key_checking '
        line: 'host_key_checking = False'

#######################################################################################################################
### Hosts
#######################################################################################################################
- hosts: host
  become: yes
  tasks:
    - include: common.yml
    - include: dns.yml
    - include: ganglia-monitor.yml
    - include: docker.yml
    - include: serf.yml
    - include: butterfly.yml
  handlers:
    - name: Restart Serf
      service:
        name: "serf"
        state: "restarted"
    - name: Restart Docker
      service:
        name: "docker"
        state: "restarted"
    - name: Restart Butterfly
      supervisorctl:
        name: "butterfly"
        state: "restarted"
    - name: Restart Supervisor
      supervisorctl:
        name: "supervisor"
        state: "restarted"
    - name: Restart gmond
      command: service ganglia-monitor restart

#######################################################################################################################
### Coordinators
#######################################################################################################################
- hosts: host-coordinators
  become: yes
  tasks:
    - include: ganglia-master.yml

    - name: make sure the /etc/bigboards directory exists
      file:
        path: "/etc/bigboards"
        state: "directory"
        owner: "bb"
        mode: "755"

    - name: make sure the hex.yml file exists
      template:
        src: "templates/etc/bigboards/hex.yml.j2"
        dest: "/etc/bigboards/hex.yml"
        owner: "bb"
        mode: "u=rx,g=r,o=r"

  handlers:
    - name: restart apache
      service:
        name: "apache2"
        status: "restarted"

    # gmetad and ganglia-monitor init scripts does not support `status` argument.
    - name: restart gmetad
      command: service gmetad restart