---
- hosts: host
  sudo: yes
  tasks:
## ####################################################################################################################
## ANSIBLE
## ####################################################################################################################
- hosts: host-coordinators
  sudo: yes
  tasks:
    - name: be sure host key checking is disabled
      lineinfile:
        dest: '/etc/ansible/ansible.cfg'
        regexp: 'host_key_checking '
        insertafter: '^#host_key_checking '
        line: 'host_key_checking = False'

## ####################################################################################################################
## HDD
## ####################################################################################################################
- hosts: host
  sudo: yes
  tasks:
    - name: be sure the harddisk is initialized
      shell: creates=/dev/sda1 parted -s /dev/sda mklabel msdos mkpart primary 0% 100%

    - name: be sure the harddrive filesystem has been created
      shell: creates=/root/.sda1.initialized mkfs.ext4 /dev/sda1 && touch /root/.sda1.initialized

    - name: be sure the data mountpoint exists
      file: state=directory path=/data owner=bb group=bigboards

    - name: be sure the correct FSTAB file is installed
      template: src=templates/etc/fstab-{{ ansible_machine }} dest=/etc/fstab

    - name: be sure the data directory is mounted
      shell: creates=/data/lost+found mount /data

    - name: be sure anyone can write in the data directory
      file: state=directory path=/data owner=bb group=bigboards mode=777

## ####################################################################################################################
## BUTTERFLY
## ####################################################################################################################
- hosts: host
  sudo: yes
  tasks:
    - name: make sure the software is installed
      apt:
        name: "{{ item }}"
        state: "latest"
      with_items:
        - libffi-dev
        - supervisor
        - python-dev
        - python-setuptools

    - name: make sure supervisor runs as the root user
      template:
        src: "templates/etc/init.d/supervisor"
        dest: "/etc/init.d/supervisor"
      notify: Restart Supervisor

    - name: make sure supervisor is started and will start at boot
      service:
        name: "supervisor"
        state: "started"
        enabled: "yes"

    # Ubuntu 14.04 or some install/upgrade seems to break
    # pip in combination with the requests module
    #
    # http://stackoverflow.com/questions/27318535/pip-install-traceback-error-while-installing-packages-in-python
    # https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991
    #
    # suggested fix = easy_install -U pip
    #
    # Not sure if this is the best approach as we loose control over the exact version that's being installed.
    # Or would if be better to keep our Hexes at the latest Ubuntu version (apt-get upgrade)?
    - name: make sure pip is upgraded
      shell: easy_install -U pip

    - name: make sure butterfly is installed
      pip:
        name: "butterfly"
        state: "present"

    - name: make sure the butterfly supervisord file is up to date
      template:
        src: "templates/etc/supervisor/conf.d/butterfly.conf"
        dest: "/etc/supervisor/conf.d/butterfly.conf"
      notify: Restart Butterfly

  handlers:
    - name: Restart Butterfly
      supervisorctl:
        name: "butterfly"
        state: "restarted"
    - name: Restart Supervisor
      supervisorctl:
        name: "supervisor"
        state: "restarted"

## ####################################################################################################################
## SERF
## ####################################################################################################################
- hosts: host
  sudo: yes
  tasks:
    - name: be sure the serf home directoy has been created
      file:
        path: '{{item}}'
        state: 'directory'
      with_items:
        - '/etc/serf'
        - '/opt/serf'
        - '/opt/serf/bin'

    - name: be sure serf is installed
      copy:
        src: 'files/{{ansible_machine}}/serf'
        dest: '/opt/serf/bin/serf'
        mode: 755
      notify: Restart Serf

    - name: be sure there is a link to serf
      file:
        src: "/opt/serf/bin/serf"
        dest: "/usr/bin/serf"
        state: "link"

    - name: be sure the serf files are up to date
      template:
        src: 'templates/{{ item }}'
        dest: '/{{ item }}'
      with_items:
        - etc/default/serf
        - etc/init/serf.conf
        - etc/network/if-down.d/serf
        - etc/network/if-up.d/serf
        - etc/dhcp/dhclient-exit-hooks.d/serf
      notify: Restart Serf

    - name: be sure serf has the right configuration
      template:
        src: 'templates/etc/serf/serf.conf'
        dest: '/etc/serf/serf.conf'
      notify: Restart Serf

  handlers:
    - name: Restart Serf
      shell: service serf restart

## ####################################################################################################################
## DOCKER.IO
## ####################################################################################################################
- hosts: host
  sudo: yes
  tasks:
    - name: be sure docker is installed ( + dependencies )
      apt:
        name: '{{ item }}'
        state: 'latest'
      with_items:
        - docker.io
        - python-pip
        - python-dev
        - build-essential
      notify: Restart Docker

    - name: make sure the docker data directory exists
      file:
        state: 'directory'
        path: '/data/docker'
        owner: 'bb'
        mode: '777'

    - name: be sure the requests package for python is removed
      file:
        path: '/usr/local/lib/python2.7/dist-packages/requests'
        state: 'absent'
      notify: Restart Docker

    - name: be sure the docker python bindings are installed
      pip:
        name: 'docker-py'
        state: 'latest'
      notify: Restart Docker


    - name: be sure the docker defaults are updated
      notify: Restart Docker
      copy:
        src: 'templates/etc/default/docker.io'
        dest: '/etc/default/docker.io'
        owner: 'root'
        group: 'root'
        mode: 644

    - name: be sure the docker upstart script is updated
      notify: Restart Docker
      copy:
        src: 'templates/etc/init/docker.io.conf'
        dest: '/etc/init/docker.io.conf'
        owner: 'root'
        group: 'root'
        mode: 644

## LIBRARIES ##################################################################

    - name: make sure docker can reach its depending libraries
      notify: Restart Docker
      when: ansible_machine == 'armv7l'
      file:
        src: '/lib/arm-linux-gnueabihf/libdevmapper.so.1.02.1'
        dest: '/lib/arm-linux-gnueabihf/libdevmapper.so.1.02'
        state: 'link'

    - name: make sure docker can reach its depending libraries
      notify: Restart Docker
      when: ansible_machine == 'x86_64'
      file:
        src: '/lib/x86_64-linux-gnu/libdevmapper.so.1.02.1'
        dest: '/lib/x86_64-linux-gnu/libdevmapper.so.1.02'
        state: 'link'

## DOCKER BINARY ##############################################################

    - name: make sure we use version 1.5.0 of the docker binary
      notify: Restart Docker
      copy:
        src: 'files/{{ ansible_machine }}/docker-1.5.0'
        dest: '/usr/bin/docker-1.5.0'
        mode: 777

    - name: make sure the docker file is removed before attempting to link it
      notify: Restart Docker
      file:
        path: '/usr/bin/docker'
        state: 'absent'

    - name: make sure the links for the docker binary are correct
      notify: Restart Docker
      file:
        src: '/usr/bin/{{item.src}}'
        dest: '/usr/bin/{{item.dest}}'
        mode: 777
        state: 'link'
      with_items:
        - { src: 'docker-1.5.0', dest: 'docker' }
        - { src: 'docker-1.5.0', dest: 'docker.io' }

## DOCKERINIT BINARY ##########################################################

    - name: make sure we use version 1.5.0 of the dockerinit binary
      when: ansible_machine == 'armv7l'
      notify: Restart Docker
      copy:
        src: 'files/{{ ansible_machine }}/dockerinit-1.5.0'
        dest: '/usr/lib/docker.io/dockerinit-1.5.0'
        mode: 755

    - name: make sure the docker file is removed before attempting to link it
      when: ansible_machine == 'armv7l'
      notify: Restart Docker
      file:
        path: '/usr/lib/docker.io/dockerinit'
        state: 'absent'

    - name: make sure the links for the docker binary are correct
      when: ansible_machine == 'armv7l'
      notify: Restart Docker
      file:
        src: '/usr/lib/docker.io/dockerinit-1.5.0'
        dest: '/usr/lib/docker.io/dockerinit'
        mode: 755
        state: 'link'

    - name: make sure the docker.io libraries are linked to docker
      when: ansible_machine == 'armv7l'
      notify: Restart Docker
      file:
        src: '/usr/lib/docker.io'
        dest: '/usr/lib/docker'
        mode: 755
        state: 'link'

  handlers:
    - name: Restart Docker
      command: service docker.io restart
