---
- hosts: host
  sudo: yes
  tasks:
    - name: be sure the docker version is up to date
      copy: src=files/docker-1.3.0 dest=/usr/bin/docker
      notify: Restart Docker

  handlers:
    - name: Restart Docker
      service: name=docker.io state=restarted