- name: restart apache
  service: name=apache2 state=restarted

# gmetad and ganglia-monitor init scripts does not support `status`
# argument.
- name: restart gmetad
  command: service gmetad restart