- hosts: "all:!localhost"
  become: "yes"
  tasks:
  - name: "List running containers"
    shell: "docker ps |cut -d ' ' -f1 |grep -v CONTAINER"
    register: "docker_running"
    failed_when: "docker_running.rc > 1"

  - name: "Debug running containers"
    debug:
      var: "docker_running"

  - name: "Stop running containers"
    shell: "docker stop --time=10 {{ item }}"
    ignore_errors: "yes"
    with_items: "{{docker_running.stdout_lines}}"

  - name: "List available containers"
    shell: "docker ps -a |cut -d ' ' -f1 |grep -v CONTAINER"
    register: "docker_available"
    failed_when: "docker_available.rc > 1"

  - name: "Remove available containers"
    shell: "docker rm -f {{ item }}"
    ignore_errors: "yes"
    with_items: "{{docker_available.stdout_lines}}"

  - name: "Remove data directories"
    file:
      path: "/data/{{ item }}"
      state: "absent"
    with_lines: 'find /data/ ! -readable -prune -type f -printf "%P\n"'

- hosts: "localhost"
  become: "yes"
  tasks:
    - name: "Remove tints information"
      file:
        path: "/opt/bb/tints.d/{{item}}"
        state: "absent"
      with_items:
        - "stack"
        - "dataset"
        - "tutor"
    - name: "Reset installed tints meta information"
      copy:
        dest: "/opt/bb/tints.d/meta.json"
        content: "[]"
    - name: "Restart mmc"
      service:
        name: "bigboards-mmc"
        state: "restarted"